### ISSUE TITLE
Literal out of range errors from overflowing_literals lint

### ISSUE THREAD

**Issue by ollie27** [jrmuizel/pdf-extract#10]
In a future version of Rust the `overflowing_literals` lint will become deny by default. See rust-lang/rust#55632. When checking for breakage in crates uploaded to crates.io it was discovered that this crate will no longer compile thanks to this lint. The error produced is [here](https://crater-reports.s3.amazonaws.com/pr-55632/try%23dc13be39fae8d4c607889b27de374b52586485a3/reg/pdf-extract-0.4.6/log.txt).

**Comment by anfractuosity** [comment]
I commented out '//("Digamma", 0x1d7cb)' which fixed the compilation issue for me on the latest rust stable.  I'm sure there's a better way to fix this, but I'm not familiar with pdf too much.

**Comment by jrmuizel** [comment]
I pushed a fix
