### ISSUE TITLE
how to compile + run examples/extract.rs from cargo?

### ISSUE THREAD

**Issue by efx** [jrmuizel/pdf-extract#2]
HI, thanks for building this; looks useful to grab text from PDF's using rust.
I'm new to rust so forgive my ignorance here.
I had to copy `examples/extract.rs` to `lib/main.rs` to be able to do `cargo run some.pdf`. Is there a way to compile `examples/extract.rs` directly?
I saw this error when trying:
```
» rustc examples/extract.rs 
error[E0463]: can't find crate for `pdf_extract`
 --> examples/extract.rs:1:1
  |
1 | extern crate pdf_extract;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

**Comment by jrmuizel** [comment]
cargo run --example extract some.pdf
