### ISSUE TITLE
Performance: use nom_parser in lopdf instead of pom_parser

### ISSUE THREAD

**Issue by badicsalex** [jrmuizel/pdf-extract#33]
Apparently lopdf is also changing to nom_parser as a default, but since this is forced in pdf-extract's Cargo.toml, it should be modified there too.
The performance change is dramatic, for one of my sample files I get a 60%+ reduction in runtime.

See https://github.com/J-F-Liu/lopdf/issues/157

**Comment by jrmuizel** [comment]
pdf-extract uses nom-parser now.
