### ISSUE TITLE
DeviceN colorspace is not supported

### ISSUE THREAD

**Issue by badicsalex** [jrmuizel/pdf-extract#40]
Hi,

I got a panic parsing http://www.kozlonyok.hu/nkonline/mkpdf/hiteles/mk13190.pdf: 
thread 'main' panicked at 'color_space [67, 83, 48] "DeviceN" [/DeviceN, [/Black], /DeviceCMYK, 1565 0 R, 1562 0 R]', src/lib.rs

**Comment by jrmuizel** [comment]
Fixed by 47898583ce0ab32b3fc4b1006395f716a0557aae
