### ISSUE TITLE
`pdf_extract::extract_text` returns an empty string for a non-empty PDF

### ISSUE THREAD

**Issue by baarkerlounger** [jrmuizel/pdf-extract#43]
`pdf_extract::extract_text` returns an empty string for a non-empty PDF. Are there PDF attributes that are known not to work I should check for? Or anything else I can do to to narrow down the issue? (I don't have a reproducible case I can share unfortunately).

**Comment by jrmuizel** [comment]
Is the `show_text` function being called at all?

**Comment by baarkerlounger** [comment]
No it isn't

**Comment by jrmuizel** [comment]
Is the pdf encrypted?

**Comment by baarkerlounger** [comment]
Also no

**Comment by jrmuizel** [comment]
Can you select and copy the text successfully if you load it here: https://mozilla.github.io/pdf.js/web/viewer.html?

**Comment by baarkerlounger** [comment]
Yep, that works fine

**Comment by baarkerlounger** [comment]
It looks like 

```rust
# lib.rs:1351

lopdf::Content::decode(&content).unwrap();
```

Only returns `Content { operations: [Operation { operator: "q", operands: [] }] }` which seems unlikely to be correct? Possibly the issue is in lopdf?

**Comment by jrmuizel** [comment]
Yeah, it seems like it's probably a problem in lopdf.

**Comment by baarkerlounger** [comment]
Have opened an issue upstream https://github.com/J-F-Liu/lopdf/issues/192 and will close this
