### ISSUE TITLE
Processing pollutes stderr 

### ISSUE THREAD

**Issue by SirVer** [jrmuizel/pdf-extract#5]
I see a ton of errors or meta data printed when running the example script. Using this in a CLI app makes the app not very useful to end users. Can the verbosity made configurable?

**Comment by jrmuizel** [comment]
It's currently all hard coded using println!() I can land something that turns that off.

**Comment by jrmuizel** [comment]
I've fixed this now.

**Comment by SirVer** [comment]
That was a quick turnaround :). Thanks!
