### ISSUE TITLE
RUSTSEC-2021-0153  Switch to Encoding RS?

### ISSUE THREAD

**Issue by pvichivanives** [jrmuizel/pdf-extract#90]
Hi! Was wondering if the library could change to using a maintained encoding library such as: https://crates.io/crates/encoding_rs 
From encoding since as seen from the Rust Security Advisory Database, Encoding is unmaintained and hasn't been updated for nearly 8 years?

https://rustsec.org/advisories/RUSTSEC-2021-0153

**Comment by jrmuizel** [comment]
Sure, I'd accept a PR to do that.
